setwd("U:/My Documents/_research/R-working/gsea")
text_files <- list.files(path = "U:/My Documents/_research/R-working/gsea/gsea-data",               pattern = "*.txt", full.names = TRUE)
target_folder <- getwd()
file.copy(text_files, target_folder)
old_names <- list.files(path = target_folder, pattern = "*.txt", full.names = FALSE)
targets <- c(" ", "-", ".txt")
replacements <- c("_", "_", "")
temp_names <- gsub(targets[1], replacements[1], old_names)
new_names <- gsub(targets[2], replacements[2], temp_names)
file.rename(old_names, new_names)
object_names <- substr(new_names,1,regexpr(".txt", new_names)-1)
temp <- lapply(new_names, read.table, sep = "\t", header = FALSE)
names(temp) <- object_names
